import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "個人網站-最終任務",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant-TW">
      <body className={`${inter.className}`}>
        <div className="mx-auto max-w-[1920px]">
          <Header />
          <main className="flex min-h-screen w-full flex-col items-center justify-between">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
